/////////////////////////////////////////////////////////////
// cxr_test.h
//
// This file was generated by CXR, the literal string encryptor.
// CXR, Copyright 2002, Smaller Animals Software, Inc., all rights reserved.
//
// Please do not edit this file. Any changes here will be overwritten on the next compile.
// If you wish to make changes to a string, please edit:
//     test.cxr
//

/////////////////////////////////////////////////////////////

#pragma once
#include "cxr_inc.h"

// cxr 적용 테스트입니당

///////////////////////////
#ifdef _USING_CXR
#define STR_CXRTEST1 	_CXR("\x8e\x82\x86\x83\x8b\x8c\x8f\x8b\x81\x8a\x83\x8c\x8d\x81\x87\x80\x89\x87\x82\x8c\x82\x8b\x83\x88\x84\x8d\x8a\x80\x85\x85\x85\x82\x8c\x8c\x8e\x8f\x89\x81\x85\x8d\x8a\x8e\x8a\x8e\x88\x85\x89\x8b\x89\x8d\x81\x8d\x81\x8d\x83\x83\x8c\x82\x86\x85\x85\x8f\x82\x8e\x81\x8f")
#else
#define STR_CXRTEST1 _CXR("Your all bases are belong to us.")
#endif

///////////////////////////
#ifdef _USING_CXR
#define STR_CXRTEST2 	_CXR("\x8f\x89\x80\x83\x87\x85\x84\x8e\x8a\x8c\x82\x89\x88\x84\x85\x8f\x88\x88\x82\x87")// 디파인 뒤에 주석이 달린 경우를 테스트
#else
#define STR_CXRTEST2 _CXR("It's You!")// 디파인 뒤에 주석이 달린 경우를 테스트
#endif

///////////////////////////
#ifdef _USING_CXR
#define STR_CXRTEST3 	_CXR("\x83\x8e\x8d\x8d\x8c\x8c\x83\x80\x80\x89")		// 디파인 뒤에 공백을 두고 주석이 달린 경우를 테스트
#else
#define STR_CXRTEST3 _CXR("Aye.")		// 디파인 뒤에 공백을 두고 주석이 달린 경우를 테스트
#endif


